

########################
## DEFINE CONFIG SCHEMA
default:

  ## PROJECT DETAILS AND FILE PATH ROOTS
  project_name: ""
  survey_name: ""
  root_path: ""
  user_path: ""


  ## PATHWAYS WORKBOOK PARAMETERS

  # WHEN = FALSE, EXISTING WORKBOOOK WILL BE IMPORTED IN 1_setup.R SCRIPT
  # WHEN = TRUE, A NEW PATHWAYS WORKBOOK WILL BE CREATED IN THE 2_data_cleaning.R SCRIPT
  create_new_pathways_workbook: FALSE

  # DEFINE NAME FOR EXISTING PATHWAYS WORKBOOK
  # DEFINE NAME FOR NEW PATHWAYS WORKBOOK
  pathways_workbook_path: ""
  new_pathways_workbook_path: ""


  ## MAPPING VARIABLES

  # NAME OF SHP FILE
  # NAME OF STATE VARIABLE IN SURVEY DATASET
  shp_file: ""
  data_state_var: ""


  # SURVEY DESIGN VARIABLES

  # USE SURVEY WEIGHTS IN ANALYSIS
  # SURVEY DESIGN ID
  # SURVEY DESIGN STRATA
  use_svy_design: TRUE
  svy_id_var: ""
  svy_strata_var: ""





