

########################
## DEFINE CONFIG SCHEMA
default:

  ## PROJECT DETAILS AND FILE PATH ROOTS
  project_name: "Ethiopia DHS 2016"
  root_path: "C:/Users/jeremyco/OneDrive - Bill & Melinda Gates Foundation/scenario_dhs_ethiopia_2016/"
  user_path: "workshop_prep/"


  ## PATHWAYS WORKBOOK PARAMETERS

  # WHEN = FALSE, EXISTING WORKBOOOK WILL BE IMPORTED IN 1_setup.R SCRIPT
  # WHEN = TRUE, A NEW PATHWAYS WORKBOOK WILL BE CREATED IN THE 2_data_cleaning.R SCRIPT
  create_new_pathways_workbook: FALSE

  # DEFINE NAME FOR EXISTING PATHWAYS WORKBOOK FOLDER
  # DEFINE NAME FOR NEW PATHWAYS WORKBOOK FOLDER
  pathways_workbook_path: "pathways_data_dictionary"
  new_pathways_workbook_path: "pathway_results


  ## MAPPING VARIABLES

  # NAME OF SHP FILE
  # NAME OF STATE VARIABLE IN SURVEY DATASET
  shp_file: "gadm41_ETH_shp/gadm41_ETH_1.shp"
  data_state_var: "v024"


  # SURVEY DESIGN VARIABLES

  # USE SURVEY WEIGHTS IN ANALYSIS
  # SURVEY DESIGN ID
  # SURVEY DESIGN STRATA
  use_svy_design: TRUE
  svy_id_var: "v021"
  svy_strata_var: "v023"





